controller_joint_names: ['l1_joint', 'l2_joint', 'l3_joint', 'l4_joint', 'l5_joint', 'l6_joint', 'lg1_joint', 'lg2_joint', 'r1_joint', 'r2_joint', 'r3_joint', 'r4_joint', 'r5_joint', 'r6_joint', 'rg3_joint', 'rg4_joint', ]
