group_controller:

  type: position_controllers/JointTrajectoryController

  joints:

     - base_r_1_joint

     - r_1_r_2_joint

     - r_2_r_3_joint

     - r_3_r_4_joint

     - r_4_r_5_joint

     - r_arm_wrist_flex_joint

     - r_gripper_finger_joint






  constraints:

      goal_time: 0.6

      stopped_velocity_tolerance: 0.05

      base_r_1_joint: {trajectory: 0.1, goal: 0.1}

      r_1_r_2_joint: {trajectory: 0.1, goal: 0.1}

      r_2_r_3_joint: {trajectory: 0.1, goal: 0.1}     

      r_2_r_3_joint: {trajectory: 0.1, goal: 0.1}

      r_3_r_4_joint: {trajectory: 0.1, goal: 0.1}

      r_4_r_5_joint: {trajectory: 0.1, goal: 0.1}

      r_arm_wrist_flex_joint: {trajectory: 0.1, goal: 0.1}

      r_gripper_finger_joint: {trajectory: 0.1, goal: 0.1}



  stop_trajectory_duration: 0.5

  state_publish_rate:  25

  action_monitor_rate: 10
